export const Colors = {
  primary: '#87361d',
  onPrimary: '#ffffff',
  primaryContainer: '#a64d32',
  onPrimaryContainer: '#ffe0d8',
  inversePrimary: '#ffb59f',
  primaryFixed: '#ffdbd1',
  primaryFixedDim: '#ffb59f',
  onPrimaryFixed: '#3a0a00',
  onPrimaryFixedVariant: '#7c2e15',

  secondary: '#655d53',
  onSecondary: '#ffffff',
  secondaryContainer: '#ece1d3',
  onSecondaryContainer: '#6b6359',
  secondaryFixed: '#ece1d3',
  secondaryFixedDim: '#cfc5b8',
  onSecondaryFixed: '#201b13',
  onSecondaryFixedVariant: '#4c463c',

  tertiary: '#3a572e',
  onTertiary: '#ffffff',
  tertiaryContainer: '#517044',
  onTertiaryContainer: '#cef2bb',
  tertiaryFixed: '#c9edb6',
  tertiaryFixedDim: '#aed09c',
  onTertiaryFixed: '#052101',
  onTertiaryFixedVariant: '#314e26',

  error: '#ba1a1a',
  onError: '#ffffff',
  errorContainer: '#ffdad6',
  onErrorContainer: '#93000a',

  surface: '#fbf9f4',
  surfaceDim: '#dbdad5',
  surfaceBright: '#fbf9f4',
  surfaceContainerLowest: '#ffffff',
  surfaceContainerLow: '#f5f3ee',
  surfaceContainer: '#f0eee9',
  surfaceContainerHigh: '#eae8e3',
  surfaceContainerHighest: '#e4e2dd',
  surfaceVariant: '#e4e2dd',
  surfaceTint: '#9a442a',
  onSurface: '#1b1c19',
  onSurfaceVariant: '#55423d',
  inverseSurface: '#30312e',
  inverseOnSurface: '#f2f1ec',
  outline: '#88726c',
  outlineVariant: '#dcc1ba',

  background: '#fbf9f4',
  onBackground: '#1b1c19',

  white: '#ffffff',
  black: '#000000',
  star: '#F59E0B',
  skeletonBase: '#F1EFE9',
  skeletonHighlight: '#E5E2DA',
  divider: '#F1EFE9',
  border: '#E5E2DA',
} as const;
